### ISSUE TITLE
Create an intro

### ISSUE THREAD

**Issue by Mauro2105** [Mauro2105/homepage#4]
Add an intro about yourself: who are you, what is your strength, why are you here.

### Description
Hello, my name is Mauricio Bermúdez. I am an engineer currently exploring the world of technologies. I am not currently employed, but I enjoy continuous learning and exercising. I am a committed person and always strive to improve my skills and knowledge.

### Tasks
- [ ] Introduce myself: Mauricio Bermúdez, Mechanical Engineer
- [ ] Friendly, responsible, committed to my work
- [ ] I am here because I want new opportunities, to explore this new world, and to continue growing professionally

**Comment by Mauro2105** [comment]
Add an intro about yourself: who are you, what is your strength, why are you here.
